plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - AccessibleVisualContent.md
  - Questions_and_answers.md
  - README.md
  - TitleIX.md
  - dockerBasicInstructions.md
  - dockerInstallation.md
  - git&Github.md
  - minimumPEP8.md
  - weeklyReportTemplate.md

theme: jekyll-theme-tactile
